### ISSUE TITLE
App crashes on startup on Fairphone 4

### ISSUE THREAD

**Issue by clawoflight** [izderadicka/audioserve-android#28]
The app briefly opens (I see "recently listened" for a blink of an eye) and then crashes.
This might be a CPU architecture issue: I think the FP4 is aarch64.

Everything worked perfectly on my previous phone and on my wife's.
I would appreciate any help or information :)

**Comment by izderadicka** [comment]
Log information would be need. For Android there are several options, command line adb logcat, Android studio logcat window, or some android app that is logcat viewer. Search net for "android logcat" for details. Also as first information android version is needed.

**Comment by izderadicka** [comment]
and version of audioserve app

**Comment by clawoflight** [comment]
I'm on Android 11, app version 0.8.7 from github release.

```02-12 19:53:25.179  2651  2651 D CarrierConfigLoader: getConfigForSubIdWithFeature subid: 1 phoneid: 0 callingPackage: com.android.phone
02-12 19:53:25.596  1242  2728 E ANDR-PERF-JNI: com_qualcomm_qtiperformance_native_perf_io_prefetch_start
02-12 19:53:25.599   950  1025 E ANDR-IOP: io prefetch is disabled
02-12 19:53:25.607  1242  2728 D CompatibilityInfo: mCompatibilityFlags - 0
02-12 19:53:25.607  1242  2728 D CompatibilityInfo: applicationDensity - 400
02-12 19:53:25.607  1242  2728 D CompatibilityInfo: applicationScale - 1.0
02-12 19:53:25.608   955   955 W ANDR-PERF-LM: WQ: push() 54: LMTriggerQ push() size=25 mFlushThreshold=25, Reached threshold => flooding detected, clearing Queue
02-12 19:53:25.608  1242  2728 D ActivityTrigger: ActivityTrigger activityPauseTrigger
02-12 19:53:25.625  1242  1606 D CompatibilityChangeReporter: Compat change id reported: 135634846; UID 10289; state: DISABLED
02-12 19:53:25.625  1242  1606 D CompatibilityChangeReporter: Compat change id reported: 135754954; UID 10289; state: DISABLED
02-12 19:53:25.625  1242  1663 D CompatibilityChangeReporter: Compat change id reported: 143937733; UID 10289; state: DISABLED
02-12 19:53:25.634   766   766 D Zygote  : Forked child process 10476
02-12 19:53:25.636  1242  1663 I ActivityManager: Start proc 10476:eu.zderadicka.audioserve/u0a289 for pre-top-activity {eu.zderadicka.audioserve/eu.zderadicka.audioserve.MainActivity}
02-12 19:53:25.642 10476 10476 I libc    : SetHeapTaggingLevel: tag level set to 0
02-12 19:53:25.647 10476 10476 E icka.audioserv: Not starting debugger since process cannot load the jdwp agent.
02-12 19:53:25.656  1242  3439 D CompatibilityInfo: mCompatibilityFlags - 0
02-12 19:53:25.656  1242  3439 D CompatibilityInfo: applicationDensity - 400
02-12 19:53:25.656  1242  3439 D CompatibilityInfo: applicationScale - 1.0
02-12 19:53:25.659  1242  3439 D CompatibilityInfo: mCompatibilityFlags - 0
02-12 19:53:25.659  1242  3439 D CompatibilityInfo: applicationDensity - 400
02-12 19:53:25.659  1242  3439 D CompatibilityInfo: applicationScale - 1.0
02-12 19:53:25.668 10476 10476 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
02-12 19:53:25.674 10476 10476 I Perf    : Connecting to perf service.
02-12 19:53:25.677 10476 10476 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-12 19:53:25.677 10476 10476 D NetworkSecurityConfig: No Network Security Config specified, using platform default
02-12 19:53:25.689  4099 16090 D iris@ForegroundUtils: onForegroundActivitiesChanged: pid = 10476, uid = 10289, foregroundActivities = true
02-12 19:53:25.691  4099 16090 D iris@ForegroundUtils: Id: 10476 ProcessName: eu.zderadicka.audioserve  Label: audioserve
02-12 19:53:25.691  4099 16090 D iris@ForegroundUtils: dispatchActivityChanged: pkg = eu.zderadicka.audioserve
02-12 19:53:25.696  4099 16090 D iris@ForegroundUtils: dispatchActivityChanged: 1234, pkg = eu.zderadicka.audioserve
02-12 19:53:25.696  4099 16090 D iris@ForegroundUtils: dispatchActivityChanged: 2222
02-12 19:53:25.696  4099 16090 D nxt@AbsFeatrueService: onUidToForeground2() called with: pkg = [eu.zderadicka.audioserve], cls = [], activityType = [-1]
02-12 19:53:25.696  4099 16090 D Iris3EnhanceService: doCheckSdr2Hdr() called with: pkg = [eu.zderadicka.audioserve], cls = [], activityType = [-1]
02-12 19:53:25.706   995  2842 W DisplayIdentification: Invalid EDID: falling back to serial number due to missing display name.
02-12 19:53:25.706   995  2842 W DisplayIdentification: Invalid EDID: falling back to ASCII text due to missing serial number.
02-12 19:53:25.722  4099 16090 I iris@ForegroundUtils: onTaskStackChanged
02-12 19:53:25.765 10476 10476 D Main    : Created main activity with action android.intent.action.MAIN
02-12 19:53:25.775 10476 10476 D ControllerFragment: ControllerFragment.onStart
02-12 19:53:25.775 10476 10476 D FolderFragment: onMediaServiceConnect android.support.v4.media.MediaBrowserCompat@5d68a53
02-12 19:53:25.777  1242  3439 D CompatibilityInfo: mCompatibilityFlags - 0
02-12 19:53:25.777  1242  3439 D CompatibilityInfo: applicationDensity - 400
02-12 19:53:25.777  1242  3439 D CompatibilityInfo: applicationScale - 1.0
02-12 19:53:25.790  1242  4668 D CompatibilityInfo: mCompatibilityFlags - 0
02-12 19:53:25.790  1242  4668 D CompatibilityInfo: applicationDensity - 400
02-12 19:53:25.790  1242  4668 D CompatibilityInfo: applicationScale - 1.0
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: QUALCOMM build                   : 9fb8420ccd, I4cee0650f2
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Build Date                       : 05/17/21
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.12
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Local Branch                     :
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Remote Branch                    :
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Remote Branch                    :
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Reconstruct Branch               :
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
02-12 19:53:25.806 10476 10502 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
02-12 19:53:25.809 10476 10502 I AdrenoGLES-0: PFP: 0x016ee197, ME: 0x00000000
02-12 19:53:25.861 10476 10476 D audioserve-service: Initializing PlayerController
02-12 19:53:25.866  5882  6043 D HeadsetService: getHeadsetService(): returning com.android.bluetooth.hfp.HeadsetService@4ea2375
02-12 19:53:25.867  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.867  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.867  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.867  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.867  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.872  1242  1653 I ActivityTaskManager: Displayed eu.zderadicka.audioserve/.MainActivity: +273ms
02-12 19:53:25.872  5882  6043 V Avrcp_ext: ActiveSession: MediaController (au.com.shiftyjelly.pocketcasts@2a81d55) <SNIP>
02-12 19:53:25.873  5882  6043 V Avrcp_ext: isBrowseSupported for au.com.shiftyjelly.pocketcasts: false
02-12 19:53:25.873  5882  6043 D Avrcp_ext: Adding media player info for au.com.shiftyjelly.pocketcasts with id 4
02-12 19:53:25.873 10476 10476 I ExoPlayerImpl: Init da845f3 [ExoPlayerLib/2.9.1] [FP4, FP4, Fairphone, 30]
02-12 19:53:25.875  5882  6043 D Avrcp_ext: update #4:MediaPlayerInfo au.com.shiftyjelly.pocketcasts (as 'Pocket Casts') Type = 1, SubType = 0, Status = 0 Feature Bits [40 41 42 44 45 47 48 58] Controller: MediaController (au.com.shiftyjelly.pocketcasts@2a81d55) <SNIP>
02-12 19:53:25.875  5882  6043 V Avrcp_ext: updateCurrentMediaState: mMediaController: MediaController (com.google.android.youtube@e4f1e12) null, null, null
02-12 19:53:25.875  5882  6043 V Avrcp_ext: isMusicActive: false getBluetoothPlayState: 0
02-12 19:53:25.875  5882  6043 V Avrcp_ext: updateCurrentMediaState: get media attributes:
02-12 19:53:25.875  5882  6043 D Avrcp_ext: overwrite album_artist :if album is blank
02-12 19:53:25.876  5882  6043 D Avrcp_ext:  albumName : device :null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: Media update: id -1➡-1? [MediaAttributes:  -  by  (0 0/0) ] : [MediaAttributes:  -  by  (0 0/0) ]
02-12 19:53:25.876  5882  6043 D Avrcp_ext: isPackageNameValid: browsedPackage = com.google.android.youtubeisValid = true
02-12 19:53:25.876  5882  6043 V Avrcp_ext: isBrowseSupported for com.google.android.youtube: false
02-12 19:53:25.876  5882  6043 V Avrcp_ext: newPlayStatus:0mReportedPlayStatus:-1
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState, state: PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null} device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: Device: no name:
02-12 19:53:25.876  5882  6043 I chatty  : uid=1002(bluetooth) BluetoothAvrcpH identical 3 lines
02-12 19:53:25.876  5882  6043 V Avrcp_ext: Device: no name:
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlayerStateAndPosition, old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}, state=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}
02-12 19:53:25.876  5882  6043 V Avrcp_ext: old state = PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}, new state= PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}
02-12 19:53:25.876  5882  6043 D HeadsetService: getHeadsetService(): returning com.android.bluetooth.hfp.HeadsetService@4ea2375
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 I Avrcp_ext: updatePlayStatusForDevice: device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0)
02-12 19:53:25.876  5882  6043 I Avrcp_ext: Exit updatePlayStatusForDevice
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 I Avrcp_ext: updatePlayStatusForDevice: device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0)
02-12 19:53:25.876  5882  6043 I Avrcp_ext: Exit updatePlayStatusForDevice
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 I Avrcp_ext: updatePlayStatusForDevice: device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0)
02-12 19:53:25.876  5882  6043 I Avrcp_ext: Exit updatePlayStatusForDevice
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 I Avrcp_ext: updatePlayStatusForDevice: device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0)
02-12 19:53:25.876  5882  6043 I Avrcp_ext: Exit updatePlayStatusForDevice
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 D HeadsetService: isScoOrCallActive(): Call Active:falseCall is Ringing:falseSCO is Active:false
02-12 19:53:25.876  5882  6043 E HeadsetStateMachine: returning mCurrentState as Disconnected
02-12 19:53:25.876  5882  6043 D HeadsetService:  isAudioOn: The number of audio connected devices 0
02-12 19:53:25.876  5882  6043 I Avrcp_ext: updatePlayStatusForDevice: device: null
02-12 19:53:25.876  5882  6043 V Avrcp_ext: updatePlaybackState (1): old=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0), new=PlaybackState {state=1, position=0, buffered position=0, speed=1.0, updated=611842861, actions=8192, custom actions=[], active item id=-1, error=null}(0)
02-12 19:53:25.876  5882  6043 I Avrcp_ext: Exit updatePlayStatusForDevice
02-12 19:53:25.876  5882  6043 D Avrcp_ext: Enter sendPlayPosNotificationRsp
02-12 19:53:25.876  5882  6043 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
02-12 19:53:25.876  5882  6043 D Avrcp_ext: Enter sendPlayPosNotificationRsp
02-12 19:53:25.876  5882  6043 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
02-12 19:53:25.876  5882  6043 D Avrcp_ext: Enter sendPlayPosNotificationRsp
02-12 19:53:25.876  5882  6043 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
02-12 19:53:25.876  5882  6043 D Avrcp_ext: Enter sendPlayPosNotificationRsp
02-12 19:53:25.876  5882  6043 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
02-12 19:53:25.877  5882  6043 D Avrcp_ext: Enter sendPlayPosNotificationRsp
02-12 19:53:25.877  5882  6043 D Avrcp_ext: sendPlayPosNotificationRsp: Not registered or requesting.
02-12 19:53:25.877  5882  6043 V Avrcp_ext: Exit updatePlayerStateAndPosition
02-12 19:53:25.882 10476 10476 D AndroidRuntime: Shutting down VM
02-12 19:53:25.882 10476 10476 E AndroidRuntime: FATAL EXCEPTION: main
02-12 19:53:25.882 10476 10476 E AndroidRuntime: Process: eu.zderadicka.audioserve, PID: 10476
02-12 19:53:25.882 10476 10476 E AndroidRuntime: java.lang.RuntimeException: Unable to create service eu.zderadicka.audioserve.AudioService: java.lang.NullPointerException: Attempt to get length of null array
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4199)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:238)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1933)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7715)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to get length of null array
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheIndex$loadFromDir$1.invoke(FileCache.kt:136)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheIndex.loadFromDir$app_release(FileCache.kt:151)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.FileCache.<init>(FileCache.kt:203)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.FileCache.<init>(FileCache.kt:166)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheManager.<init>(CacheManager.kt:210)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheManager.<init>(CacheManager.kt:168)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheManager$Companion.getInstance(CacheManager.kt:324)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.AudioService.onCreate(AudioService.kt:677)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4187)
02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	... 8 more
02-12 19:53:25.884  1242 10516 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-12 19:53:25.885  1242  4123 W ActivityTaskManager:   Force finishing activity eu.zderadicka.audioserve/.MainActivity
```

**Comment by clawoflight** [comment]
Thanks for reminding me about logcat, it's been a while since I touched Android development :D
The exception made me curious, so I looked at the code and saw that it had to do with cache access.
Just in case, I cleared all app data - and it works now.

I guess there was some issue with google settings backup when I transferred to the new phone, or something like that?
I'll close this now that it works, but maybe the closed issue will help others.

Thanks very much for audioserve and the app! And don't worry too much about the UI/UX - it's more than good enough for me **and** my wife, so that's a win!

**Comment by clawoflight** [comment]
gg

**Comment by izderadicka** [comment]
Thanks

key line in log was

```
Caused by: java.lang.NullPointerException: Attempt to get length of null array

02-12 19:53:25.882 10476 10476 E AndroidRuntime: 	at eu.zderadicka.audioserve.net.CacheIndex$loadFromDir$1.invoke(FileCache.kt:136)
```
FileCache is responsible for caching ahead audio files. I think your guess would be correct, configuration was restored from backup and something was not correct, maybe path to FileCache root?
